apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: curl
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command:
      - "/bin/sleep"
      - "3600" # sleep for 3600 seconds (1 hour)
  restartPolicy: Never
