apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: this-cannot-be-the-correct-label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      # nodePort: 30000
  type: ClusterIP